
services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - mongo
    restart: unless-stopped
    # The following environment variables are expected to be in the .env file
    # MONGO_URI: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@mongo:27017
    # MONGO_DB_NAME: rugby_tactics
    # MONGO_USER: admin
    # MONGO_PASSWORD: secretpassword

  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

volumes:
  mongodata: